INSERT INTO USER VALUES ('oliver.weichert');
INSERT INTO TASKLIST(ID,NAME,USER) VALUES(10000,'Einkaufsliste','oliver.weichert');
INSERT INTO TASK(ID,tasklist,NAME,BESCHREIBUNG,ERLEDIGT) VALUES(10000,10000,'KOHLE','5kg Profagus',false);
INSERT INTO TASK(ID,tasklist,NAME,BESCHREIBUNG,ERLEDIGT) VALUES(20000,10000,'BIER','1 Kiste',false);
INSERT INTO TASK(ID,tasklist,NAME,BESCHREIBUNG,ERLEDIGT) VALUES(30000,10000,'FLEISCH','2kg Steak',false);